title:            Grillmöbel
description:      Yeah, ein cooler Blog!
url:              https://grillmoebel.github.io

links:
  - name:         Analytisches
    url:          /anal
  - name:         Prosa
    url:          /pro
  - name:         Nichtprosa
    url:          /contra
  - name:         Musiknerdtum
    url:          /musi
  - name: 	      Kommentare zum Zeitgeschehen
    url:          /zeit
  - name: 	      wiederkehrende Rubriken
    url:          /rubr
  - name: 	      Fragmente
    url:          /frag
  - name: 	      Meta
    url:          /gril
  - name: 	      Blogroll (alt)
    url:          https://laesterasphalt.github.io/
pygments:         false
permalink:        pretty
markdown:         kramdown
redcarpet:
  extensions:
    - smart
