title:            Grillmöbel
description:      Yeah, ein cooler Blog!
url:              https://grillmoebel.github.io

links:
  - name:         Über
    url:          /about
  - name:         Blog
    url:          https://grillmoebel.github.io
    external:     false
  - name:         Kontakt
    url:          mailto:korruption@gmx.de
    external:     true
pygments:         false
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
